# Generated by Django 2.2 on 2020-11-23 01:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_url', models.URLField()),
                ('short_url', models.URLField(unique=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('visits', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Url',
                'verbose_name_plural': 'Urls',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='UrlInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_time', models.DateTimeField(auto_now_add=True)),
                ('device', models.CharField(choices=[('mobile', 'Mobile'), ('desktop', 'Desktop')], max_length=20)),
                ('browser', models.CharField(max_length=50)),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='url', to='urlShorteners.Url')),
            ],
            options={
                'verbose_name': 'Short Url Informations',
                'verbose_name_plural': 'Short Urls Informations',
                'ordering': ['-use_time', 'url'],
            },
        ),
    ]
